name: pro-blogging

services:
  app:
    build:
      context: ./dev/app
    image: pro-blogging-app:latest
    hostname: "app"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        com.pro-blogging.project: "Pro Blogging"
        com.pro-blogging.service: "app"
    depends_on:
      - postgresql
    volumes:
      - ${PWD}/src/app:/usr/src/app
    networks:
      - net-bridge
    ports:
      - "8000:8000"
    env_file:
      - ${PWD}/src/app/.dev_env
    environment:
      # Terminfo
      - COLUMNS=211
      - LINES=52

  postgresql:
    build:
      context: ./dev/postgresql
    image: pro-blogging-postgresql:latest
    hostname: "postgresql"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        com.pro-blogging.project: "Pro Blogging"
        com.pro-blogging.service: "postgresql"
    volumes:
      - postgresql_db:/var/lib/postgresql/data
    networks:
      - net-bridge
    ports:
      - "35432:5432"
    env_file:
      - ${PWD}/src/app/.dev_env
    environment:
      # Terminfo
      - COLUMNS=211
      - LINES=52

volumes:
  postgresql_db:

networks:
  net-bridge:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
